var searchData=
[
  ['bathrz_0',['BathRZ',['../structdg_1_1_bath_r_z.html',1,'dg']]],
  ['besseli0_1',['BESSELI0',['../../../matrix/html/structdg_1_1mat_1_1_b_e_s_s_e_l_i0.html',1,'dg::mat']]],
  ['bfieldp_2',['BFieldP',['../../../geometries/html/structdg_1_1geo_1_1_b_field_p.html',1,'dg::geo']]],
  ['bfieldr_3',['BFieldR',['../../../geometries/html/structdg_1_1geo_1_1_b_field_r.html',1,'dg::geo']]],
  ['bfieldt_4',['BFieldT',['../../../geometries/html/structdg_1_1geo_1_1_b_field_t.html',1,'dg::geo']]],
  ['bfieldz_5',['BFieldZ',['../../../geometries/html/structdg_1_1geo_1_1_b_field_z.html',1,'dg::geo']]],
  ['bhatp_6',['BHatP',['../../../geometries/html/structdg_1_1geo_1_1_b_hat_p.html',1,'dg::geo']]],
  ['bhatpr_7',['BHatPR',['../../../geometries/html/structdg_1_1geo_1_1_b_hat_p_r.html',1,'dg::geo']]],
  ['bhatpz_8',['BHatPZ',['../../../geometries/html/structdg_1_1geo_1_1_b_hat_p_z.html',1,'dg::geo']]],
  ['bhatr_9',['BHatR',['../../../geometries/html/structdg_1_1geo_1_1_b_hat_r.html',1,'dg::geo']]],
  ['bhatrr_10',['BHatRR',['../../../geometries/html/structdg_1_1geo_1_1_b_hat_r_r.html',1,'dg::geo']]],
  ['bhatrz_11',['BHatRZ',['../../../geometries/html/structdg_1_1geo_1_1_b_hat_r_z.html',1,'dg::geo']]],
  ['bhatz_12',['BHatZ',['../../../geometries/html/structdg_1_1geo_1_1_b_hat_z.html',1,'dg::geo']]],
  ['bhatzr_13',['BHatZR',['../../../geometries/html/structdg_1_1geo_1_1_b_hat_z_r.html',1,'dg::geo']]],
  ['bhatzz_14',['BHatZZ',['../../../geometries/html/structdg_1_1geo_1_1_b_hat_z_z.html',1,'dg::geo']]],
  ['bicgstabl_15',['BICGSTABl',['../classdg_1_1_b_i_c_g_s_t_a_bl.html',1,'dg']]],
  ['bijectivecomm_16',['BijectiveComm',['../structdg_1_1_bijective_comm.html',1,'dg']]],
  ['bmodule_17',['Bmodule',['../../../geometries/html/structdg_1_1geo_1_1_bmodule.html',1,'dg::geo']]],
  ['br_18',['BR',['../../../geometries/html/structdg_1_1geo_1_1_b_r.html',1,'dg::geo']]],
  ['buffer_19',['Buffer',['../structdg_1_1_buffer.html',1,'dg']]],
  ['buffer_3c_20index_20_3e_20',['Buffer&lt; Index &gt;',['../structdg_1_1_buffer.html',1,'dg']]],
  ['buffer_3c_20thrust_3a_3ahost_5fvector_3c_20get_5fvalue_5ftype_3c_20vector_20_3e_20_3e_20_3e_21',['Buffer&lt; thrust::host_vector&lt; get_value_type&lt; Vector &gt; &gt; &gt;',['../structdg_1_1_buffer.html',1,'dg']]],
  ['buffer_3c_20typename_20collective_3a_3abuffer_5ftype_20_3e_22',['Buffer&lt; typename Collective::buffer_type &gt;',['../structdg_1_1_buffer.html',1,'dg']]],
  ['buffer_3c_20typename_20collective_3a_3acontainer_5ftype_20_3e_23',['Buffer&lt; typename Collective::container_type &gt;',['../structdg_1_1_buffer.html',1,'dg']]],
  ['buffer_3c_20value_5ftype_20_3e_24',['Buffer&lt; value_type &gt;',['../structdg_1_1_buffer.html',1,'dg']]],
  ['buffer_3c_20vector_20_3e_25',['Buffer&lt; Vector &gt;',['../structdg_1_1_buffer.html',1,'dg']]],
  ['butchertableau_26',['ButcherTableau',['../structdg_1_1_butcher_tableau.html',1,'dg']]],
  ['butchertableau_3c_20value_5ftype_20_3e_27',['ButcherTableau&lt; value_type &gt;',['../structdg_1_1_butcher_tableau.html',1,'dg']]],
  ['bz_28',['BZ',['../../../geometries/html/structdg_1_1geo_1_1_b_z.html',1,'dg::geo']]]
];
